name: deploy NodeJS Application to EC2 instance.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script:
            cd /home/ubuntu/Nodejs-App-Deploy-Github-Actions \
            git pull \ 
            docker compose up -d --build

